package com.example.demo.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class TestUrl implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_url.id
     *
     * @mbggenerated Sun May 19 22:54:42 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_url.long_url
     *
     * @mbggenerated Sun May 19 22:54:42 CST 2019
     */
    private String longUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_url.short_url
     *
     * @mbggenerated Sun May 19 22:54:42 CST 2019
     */
    private String shortUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_url.count
     *
     * @mbggenerated Sun May 19 22:54:42 CST 2019
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_url.type
     *
     * @mbggenerated Sun May 19 22:54:42 CST 2019
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_url.create_time
     *
     * @mbggenerated Sun May 19 22:54:42 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_url.update_time
     *
     * @mbggenerated Sun May 19 22:54:42 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test_url
     *
     * @mbggenerated Sun May 19 22:54:42 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_url.id
     *
     * @return the value of test_url.id
     *
     * @mbggenerated Sun May 19 22:54:42 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_url.id
     *
     * @param id the value for test_url.id
     *
     * @mbggenerated Sun May 19 22:54:42 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_url.long_url
     *
     * @return the value of test_url.long_url
     *
     * @mbggenerated Sun May 19 22:54:42 CST 2019
     */
    public String getLongUrl() {
        return longUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_url.long_url
     *
     * @param longUrl the value for test_url.long_url
     *
     * @mbggenerated Sun May 19 22:54:42 CST 2019
     */
    public void setLongUrl(String longUrl) {
        this.longUrl = longUrl == null ? null : longUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_url.short_url
     *
     * @return the value of test_url.short_url
     *
     * @mbggenerated Sun May 19 22:54:42 CST 2019
     */
    public String getShortUrl() {
        return shortUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_url.short_url
     *
     * @param shortUrl the value for test_url.short_url
     *
     * @mbggenerated Sun May 19 22:54:42 CST 2019
     */
    public void setShortUrl(String shortUrl) {
        this.shortUrl = shortUrl == null ? null : shortUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_url.count
     *
     * @return the value of test_url.count
     *
     * @mbggenerated Sun May 19 22:54:42 CST 2019
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_url.count
     *
     * @param count the value for test_url.count
     *
     * @mbggenerated Sun May 19 22:54:42 CST 2019
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_url.type
     *
     * @return the value of test_url.type
     *
     * @mbggenerated Sun May 19 22:54:42 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_url.type
     *
     * @param type the value for test_url.type
     *
     * @mbggenerated Sun May 19 22:54:42 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_url.create_time
     *
     * @return the value of test_url.create_time
     *
     * @mbggenerated Sun May 19 22:54:42 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_url.create_time
     *
     * @param createTime the value for test_url.create_time
     *
     * @mbggenerated Sun May 19 22:54:42 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_url.update_time
     *
     * @return the value of test_url.update_time
     *
     * @mbggenerated Sun May 19 22:54:42 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_url.update_time
     *
     * @param updateTime the value for test_url.update_time
     *
     * @mbggenerated Sun May 19 22:54:42 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_url
     *
     * @mbggenerated Sun May 19 22:54:42 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", longUrl=").append(longUrl);
        sb.append(", shortUrl=").append(shortUrl);
        sb.append(", count=").append(count);
        sb.append(", type=").append(type);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}