package com.example.demo.dao.mapper;

import com.example.demo.dao.entity.TestUrl;
import com.example.demo.dao.entity.TestUrlExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TestUrlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_url
     *
     * @mbggenerated Sun May 19 22:54:42 CST 2019
     */
    int countByExample(TestUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_url
     *
     * @mbggenerated Sun May 19 22:54:42 CST 2019
     */
    int deleteByExample(TestUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_url
     *
     * @mbggenerated Sun May 19 22:54:42 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_url
     *
     * @mbggenerated Sun May 19 22:54:42 CST 2019
     */
    int insert(TestUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_url
     *
     * @mbggenerated Sun May 19 22:54:42 CST 2019
     */
    int insertSelective(TestUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_url
     *
     * @mbggenerated Sun May 19 22:54:42 CST 2019
     */
    List<TestUrl> selectByExample(TestUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_url
     *
     * @mbggenerated Sun May 19 22:54:42 CST 2019
     */
    TestUrl selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_url
     *
     * @mbggenerated Sun May 19 22:54:42 CST 2019
     */
    int updateByExampleSelective(@Param("record") TestUrl record, @Param("example") TestUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_url
     *
     * @mbggenerated Sun May 19 22:54:42 CST 2019
     */
    int updateByExample(@Param("record") TestUrl record, @Param("example") TestUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_url
     *
     * @mbggenerated Sun May 19 22:54:42 CST 2019
     */
    int updateByPrimaryKeySelective(TestUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_url
     *
     * @mbggenerated Sun May 19 22:54:42 CST 2019
     */
    int updateByPrimaryKey(TestUrl record);
}