package com.example.demo.mapper;

import java.io.Serializable;
import java.util.Date;

public class WbUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_user.boss_id
     *
     * @mbggenerated Tue Mar 19 16:02:21 CST 2019
     */
    private Integer bossId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_user.boss_name
     *
     * @mbggenerated Tue Mar 19 16:02:21 CST 2019
     */
    private String bossName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_user.threshold
     *
     * @mbggenerated Tue Mar 19 16:02:21 CST 2019
     */
    private Integer threshold;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_user.identity_status
     *
     * @mbggenerated Tue Mar 19 16:02:21 CST 2019
     */
    private Integer identityStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_user.status
     *
     * @mbggenerated Tue Mar 19 16:02:21 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_user.work_status
     *
     * @mbggenerated Tue Mar 19 16:02:21 CST 2019
     */
    private Integer workStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_user.dept_id
     *
     * @mbggenerated Tue Mar 19 16:02:21 CST 2019
     */
    private Integer deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_user.identity_id
     *
     * @mbggenerated Tue Mar 19 16:02:21 CST 2019
     */
    private Integer identityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_user.oper_id
     *
     * @mbggenerated Tue Mar 19 16:02:21 CST 2019
     */
    private Integer operId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_user.oper_name
     *
     * @mbggenerated Tue Mar 19 16:02:21 CST 2019
     */
    private String operName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_user.create_time
     *
     * @mbggenerated Tue Mar 19 16:02:21 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_user.update_time
     *
     * @mbggenerated Tue Mar 19 16:02:21 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_user.work_time
     *
     * @mbggenerated Tue Mar 19 16:02:21 CST 2019
     */
    private Date workTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wb_user
     *
     * @mbggenerated Tue Mar 19 16:02:21 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_user.boss_id
     *
     * @return the value of wb_user.boss_id
     *
     * @mbggenerated Tue Mar 19 16:02:21 CST 2019
     */
    public Integer getBossId() {
        return bossId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_user.boss_id
     *
     * @param bossId the value for wb_user.boss_id
     *
     * @mbggenerated Tue Mar 19 16:02:21 CST 2019
     */
    public void setBossId(Integer bossId) {
        this.bossId = bossId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_user.boss_name
     *
     * @return the value of wb_user.boss_name
     *
     * @mbggenerated Tue Mar 19 16:02:21 CST 2019
     */
    public String getBossName() {
        return bossName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_user.boss_name
     *
     * @param bossName the value for wb_user.boss_name
     *
     * @mbggenerated Tue Mar 19 16:02:21 CST 2019
     */
    public void setBossName(String bossName) {
        this.bossName = bossName == null ? null : bossName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_user.threshold
     *
     * @return the value of wb_user.threshold
     *
     * @mbggenerated Tue Mar 19 16:02:21 CST 2019
     */
    public Integer getThreshold() {
        return threshold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_user.threshold
     *
     * @param threshold the value for wb_user.threshold
     *
     * @mbggenerated Tue Mar 19 16:02:21 CST 2019
     */
    public void setThreshold(Integer threshold) {
        this.threshold = threshold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_user.identity_status
     *
     * @return the value of wb_user.identity_status
     *
     * @mbggenerated Tue Mar 19 16:02:21 CST 2019
     */
    public Integer getIdentityStatus() {
        return identityStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_user.identity_status
     *
     * @param identityStatus the value for wb_user.identity_status
     *
     * @mbggenerated Tue Mar 19 16:02:21 CST 2019
     */
    public void setIdentityStatus(Integer identityStatus) {
        this.identityStatus = identityStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_user.status
     *
     * @return the value of wb_user.status
     *
     * @mbggenerated Tue Mar 19 16:02:21 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_user.status
     *
     * @param status the value for wb_user.status
     *
     * @mbggenerated Tue Mar 19 16:02:21 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_user.work_status
     *
     * @return the value of wb_user.work_status
     *
     * @mbggenerated Tue Mar 19 16:02:21 CST 2019
     */
    public Integer getWorkStatus() {
        return workStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_user.work_status
     *
     * @param workStatus the value for wb_user.work_status
     *
     * @mbggenerated Tue Mar 19 16:02:21 CST 2019
     */
    public void setWorkStatus(Integer workStatus) {
        this.workStatus = workStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_user.dept_id
     *
     * @return the value of wb_user.dept_id
     *
     * @mbggenerated Tue Mar 19 16:02:21 CST 2019
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_user.dept_id
     *
     * @param deptId the value for wb_user.dept_id
     *
     * @mbggenerated Tue Mar 19 16:02:21 CST 2019
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_user.identity_id
     *
     * @return the value of wb_user.identity_id
     *
     * @mbggenerated Tue Mar 19 16:02:21 CST 2019
     */
    public Integer getIdentityId() {
        return identityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_user.identity_id
     *
     * @param identityId the value for wb_user.identity_id
     *
     * @mbggenerated Tue Mar 19 16:02:21 CST 2019
     */
    public void setIdentityId(Integer identityId) {
        this.identityId = identityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_user.oper_id
     *
     * @return the value of wb_user.oper_id
     *
     * @mbggenerated Tue Mar 19 16:02:21 CST 2019
     */
    public Integer getOperId() {
        return operId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_user.oper_id
     *
     * @param operId the value for wb_user.oper_id
     *
     * @mbggenerated Tue Mar 19 16:02:21 CST 2019
     */
    public void setOperId(Integer operId) {
        this.operId = operId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_user.oper_name
     *
     * @return the value of wb_user.oper_name
     *
     * @mbggenerated Tue Mar 19 16:02:21 CST 2019
     */
    public String getOperName() {
        return operName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_user.oper_name
     *
     * @param operName the value for wb_user.oper_name
     *
     * @mbggenerated Tue Mar 19 16:02:21 CST 2019
     */
    public void setOperName(String operName) {
        this.operName = operName == null ? null : operName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_user.create_time
     *
     * @return the value of wb_user.create_time
     *
     * @mbggenerated Tue Mar 19 16:02:21 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_user.create_time
     *
     * @param createTime the value for wb_user.create_time
     *
     * @mbggenerated Tue Mar 19 16:02:21 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_user.update_time
     *
     * @return the value of wb_user.update_time
     *
     * @mbggenerated Tue Mar 19 16:02:21 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_user.update_time
     *
     * @param updateTime the value for wb_user.update_time
     *
     * @mbggenerated Tue Mar 19 16:02:21 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_user.work_time
     *
     * @return the value of wb_user.work_time
     *
     * @mbggenerated Tue Mar 19 16:02:21 CST 2019
     */
    public Date getWorkTime() {
        return workTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_user.work_time
     *
     * @param workTime the value for wb_user.work_time
     *
     * @mbggenerated Tue Mar 19 16:02:21 CST 2019
     */
    public void setWorkTime(Date workTime) {
        this.workTime = workTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_user
     *
     * @mbggenerated Tue Mar 19 16:02:21 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", bossId=").append(bossId);
        sb.append(", bossName=").append(bossName);
        sb.append(", threshold=").append(threshold);
        sb.append(", identityStatus=").append(identityStatus);
        sb.append(", status=").append(status);
        sb.append(", workStatus=").append(workStatus);
        sb.append(", deptId=").append(deptId);
        sb.append(", identityId=").append(identityId);
        sb.append(", operId=").append(operId);
        sb.append(", operName=").append(operName);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", workTime=").append(workTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}