package com.example.demo.mapper;

import com.example.demo.mapper.WbUser;
import com.example.demo.mapper.WbUserExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface WbUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_user
     *
     * @mbggenerated Tue Mar 19 16:02:21 CST 2019
     */
    int countByExample(WbUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_user
     *
     * @mbggenerated Tue Mar 19 16:02:21 CST 2019
     */
    int deleteByExample(WbUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_user
     *
     * @mbggenerated Tue Mar 19 16:02:21 CST 2019
     */
    int deleteByPrimaryKey(Integer bossId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_user
     *
     * @mbggenerated Tue Mar 19 16:02:21 CST 2019
     */
    int insert(WbUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_user
     *
     * @mbggenerated Tue Mar 19 16:02:21 CST 2019
     */
    int insertSelective(WbUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_user
     *
     * @mbggenerated Tue Mar 19 16:02:21 CST 2019
     */
    List<WbUser> selectByExample(WbUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_user
     *
     * @mbggenerated Tue Mar 19 16:02:21 CST 2019
     */
    WbUser selectByPrimaryKey(Integer bossId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_user
     *
     * @mbggenerated Tue Mar 19 16:02:21 CST 2019
     */
    int updateByExampleSelective(@Param("record") WbUser record, @Param("example") WbUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_user
     *
     * @mbggenerated Tue Mar 19 16:02:21 CST 2019
     */
    int updateByExample(@Param("record") WbUser record, @Param("example") WbUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_user
     *
     * @mbggenerated Tue Mar 19 16:02:21 CST 2019
     */
    int updateByPrimaryKeySelective(WbUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_user
     *
     * @mbggenerated Tue Mar 19 16:02:21 CST 2019
     */
    int updateByPrimaryKey(WbUser record);
}